### ISSUE TITLE
fancyled_helpers error with AttributeError: 'module' object has no attribute 'CRGB'

### ISSUE THREAD

**Issue by devoh747** [adafruit/Adafruit_CircuitPython_FancyLED#11]
On a CPX running CP 4.1.0 and libs 4.x from 10/4 the example code https://github.com/adafruit/Adafruit_CircuitPython_FancyLED/blob/master/examples/fancyled_cpx_helper_example.py

throws..

Traceback (most recent call last):
  File "code.py", line 20, in <module>
  File "/home/travis/build/adafruit/Adafruit_CircuitPython_Bundle/libraries/helpers/fancyled/adafruit_fancyled/fastled_helpers.py", line 111, in loadDynamicGradientPalette
AttributeError: 'module' object has no attribute 'CRGB'

**Comment by devoh747** [comment]
PR #14 merged.
